### ISSUE TITLE
Coffeescript runtime bug: private static class methods

### ISSUE THREAD

**Issue by greghuc** [DanielXMoore/Civet#458] opened 2023-03-18 11:55 UTC
### Coffeescript bug (runtime error)

```
"civet coffeeCompat"

class Arithmetic

  showAddition: ->
    console.log formatAdd(1, 2)

  formatAdd = (a, b) -> "#{a} + #{b}"  

(new Arithmetic()).showAddition()
# Next line errors in CS as formatAdd is private function
# console.log Arithmetic.formatAdd(3,4)
```
in the Civet playground this compiles, but then errors at runtime with
```
ReferenceError: formatAdd is not defined
```
whilst in the coffeescript playground the code compiles and runs with output
```
1 + 2
```

### Playground links

[Coffeescript link](https://coffeescript.org/#try:class%20Arithmetic%0A%0A%20%20showAddition%3A%20-%3E%0A%20%20%20%20console.log%20formatAdd(1%2C%202)%0A%0A%20%20formatAdd%20%3D%20(a%2C%20b)%20-%3E%20%22%23%7Ba%7D%20%2B%20%23%7Bb%7D%22%20%20%0A%0A(new%20Arithmetic()).showAddition()%0A%23%20Next%20line%20errors%20in%20CS%20as%20formatAdd%20is%20private%20function%0A%23%20console.log%20Arithmetic.formatAdd(3%2C4))
[Civet link](https://civet.dev/playground?code=ImNpdmV0IGNvZmZlZUNvbXBhdCIKCmNsYXNzIEFyaXRobWV0aWMKCiAgc2hvd0FkZGl0aW9uOiAtPgogICAgY29uc29sZS5sb2cgZm9ybWF0QWRkKDEsIDIpCgogIGZvcm1hdEFkZCA9IChhLCBiKSAtPiAiI3thfSArICN7Yn0iICAKCihuZXcgQXJpdGhtZXRpYygpKS5zaG93QWRkaXRpb24oKQojIE5leHQgbGluZSBlcnJvcnMgaW4gQ1MgYXMgZm9ybWF0QWRkIGlzIHByaXZhdGUgZnVuY3Rpb24KIyBjb25zb2xlLmxvZyBBcml0aG1ldGljLmZvcm1hdEFkZCgzLDQp)

### Discussion

All the discussion in [Coffeescript runtime bug: private static class attributes](https://github.com/DanielXMoore/Civet/issues/457) also applies here.

Re the particular error, I often use this pattern for class level private static functions (which can be referenced by both other class or class-instance functions). In modern JS terms, the closest concept seems to be a [private static method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields).

**Comment by STRd6** [comment] 2023-09-13 23:01
Duplicate of #457

**Closed by STRd6** 2023-09-13 23:01 UTC
Labels: bug, coffeescript
