### ISSUE TITLE
Compiler flag to emit `"use strict"`

### ISSUE THREAD

**Issue by johndeighan** [DanielXMoore/Civet#1481] opened 2024-10-20 23:52 UTC
In my `civet.config.civet` file, I disable all of autoVar, autoLet and autoConst (complete file below). I use and love CoffeeScript, but I don't believe that any compiler can catch misspelled variable names unless you are forced to declare all variables. Here is my `main.civet` file:

```
x = 42
console.log "OK, x is #{x}"

```
I expected that when I tried to execute this file via `civet main.ts`, I'd get an error. But no, it just output:

`OK, x is 42
`
FYI, I tried to execute `civet <main.civet >main.ts` to create a TypeScript file. The file `main.ts` is:

```
x = 42
console.log(`OK, x is ${x}`)

```
so, no var, let or const. In VSCode, there's a red squiggle below the variable name x, indicating an error. And, when I try to execute the TypeScript file, I get an "x is not defined" error message.

`civet.config.civet` is:

```
export default {
    parseOptions: {
        implicitReturns: false
        autoConst: false
        autoLet: false
        autoVar: false
        coffeeBooleans: false
        coffeeClasses: true
        coffeeComment: true
        coffeeDo: false
        coffeeEq: true
        coffeeInterpolation: true
        coffeeOf: false
        
    }
}


```

**Comment by bbrk24** [comment] 2024-10-20 23:54
Ah, I think this is because you aren't in strict mode! Try putting `'use strict';` at the top of your .civet file.

**Comment by edemaine** [comment] 2024-10-21 14:02
I agree with bbrk24's analysis; outside [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), you can assign to variables without declaring them. Entering strict mode fixes the problem:

![image](https://github.com/user-attachments/assets/1f39da94-c560-4fca-8d77-1f43ec826ea7)

We should maybe have a `"civet strict"` option that emits `"use strict"`, so that this can be configured in `civet.config`.

FYI, `autoConst`, `autoLet`, `autoVar` are off by default (but if you were experimenting with `coffeeCompat`, that turns on `autoVar`). You can see this behavior by inspecting the generated `.ts` file.

> And, when I try to execute the TypeScript file, I get an "x is not defined" error message.

I can't reproduce this.

![image](https://github.com/user-attachments/assets/5cb860ea-8ecd-442b-a04c-297d09b50289)

**Comment by bbrk24** [comment] 2024-10-21 14:12
If you generate a .ts file and then compile it with `tsc`, I believe TypeScript assumes strict mode by default.

**Comment by johndeighan** [comment] 2024-10-23 02:32
I'm simply using the civet command to execute the file. FYI, I can confirm that if I put 'use strict' at the top of the file, I get the error "x is not defined".

Still, I've explicitly turned off autoVar, autoLet and autoConst, so it should be perfectly clear that I don't want variables auto-declared for the reasons I mentioned in the original post. Adding a config option that automatically puts you in strict mode would, however, solve the problem. I really don't want to have to manually put 'use strict' at the top of all my source files. Meanwhile, though, I'm probably going to preprocess my source files, e.g. to support heredoc syntax (multi-line strings are NOT heredoc - if you bother to read the rest of this message, you'll see why I say that). So, my preprocessor can add the 'use strict' for now.

Consider this statement:

func("""
   this is some text
   this is some text
   this is some text
   this is some text
   this is some text
   """, 42)

when you first encounter this, you have to skip a bunch of text to discover that a second argument was passed to the function. However, using HEREDOC syntax:

func(<<<, 42)
   this is some text
   this is some text
   this is some text
   this is some text
   this is some text

it's immediately obvious that 2 args are being passed. NOTE: My version of HEREDOC syntax is a bit different than the usual. I always terminate the heredoc with a blank line (FYI, I have my editor strip any trailing whitespace. Without that, you might see an empty line, but really it includes trailing whitespace which would cause the HEREDOC to not be terminated. Here is how it would be done using normal HEREDOC syntax:

func(<<"", 42)
   this is some text
   this is some text
   this is some text
   this is some text
   this is some text

where the block of text is terminated by a blank line.

FYI, in my implementation, I allow a line consisting of a single period to represent a blank line in the resulting string. I'm not sure I've found a real use case for that, but I thought there might be a case where you'd like to have a blank line in the resulting string. Here's how I typically use HEREDOC:

queryDB <<<, [23]
   select ID, Name
   from Users
   where ID = ?

**Comment by johndeighan** [comment] 2024-10-24 23:28
I now understand that 'use strict' is a JavaScript thing, not a civet thing. Ignore my rant about having disabled autoVar, autoLet and autoConst and expecting errors for undeclared variables. I can add the 'use string' in my preprocessor. It would be nice, though, if as suggested above, there were a config that caused that to happen automatically.

**Closed** 2024-10-29 21:05 UTC
