### ISSUE TITLE
`--typecheck` doesn't map imports randomly sometimes

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#1035] opened 2024-02-19 00:45 UTC
~~When switching node versions (e.g. with `nvm`), `--typecheck` fails to map imports only the first time it is run on the new node instance, and succeeds every time after that.~~ Edit: on further investigation it's semi-random, as if by a race condition.

I have no idea how this works, but apparently that happens.

**Comment by edemaine** [comment] 2024-02-19 17:18
I'm pretty sure this isn't a Civet issue. I could reproduce it with https://github.com/bbrk24/Trilangle/tree/civet (sometimes) on Linux (not Windows).

I think the overall issue is that you use `npx civet`, but should use `npx @danielx/civet`. It seems `npx` is a bit nondeterministic whether it runs `@danielx/civet` or the NPM package `civet` when doing `npx civet`, which is probably why resetting `nvm` does something.

**Comment by bbrk24** [comment] 2024-02-19 19:10
@edemaine I only have `@danielx/civet` installed, not `civet`. `npx` doesn't just install new packages without asking first (that's what `--yes` and `--no` are for). Furthermore, the command name doesn't have to be the same as the package name, as `npx tsc` proves.

Weirdly enough, `npx @danielx/civet` does seem to fix it locally, so I'll try it in CI and see how that goes.

**Comment by edemaine** [comment] 2024-02-19 19:17
At least one time I ran your build script, `npx` asked "install civet?" which is what led me to this conclusion. Perhaps it's a bug in npx...

**Comment by edemaine** [comment] 2024-02-19 20:01
I now suspect that this is an async issue / race condition.

**Comment by edemaine** [comment] 2024-02-19 21:45
Seems to be fixed by 395be3100981ea6b8534c1c6b7211a04922ce395 which is in v0.6.78.

**Closed by edemaine** 2024-02-19 21:45 UTC
