### ISSUE TITLE
Incorrect compilation

### ISSUE THREAD

**Issue by mixty1** [DanielXMoore/Civet#985] opened 2024-02-12 17:26 UTC
[playground link](https://civet.dev/playground?code=Y2xhc3MgU3RvcmUKICBnZXRDaG9pY2VzU3RvcmUoaWQ6IHN0cmluZyk/OiBJbnN0YW5jZVR5cGU8dHlwZW9mIENob2ljZXM+CiAgICBAZWxlbWVudHMuZmluZCguaWQgaXMgaWQpPy5vcHRpb25zLmNob2ljZXMKCgoKZXhwb3J0IGludGVyZmFjZSBJRHJvcGRvd25Qcm9wcwogIGNob2ljZXM6IEluc3RhbmNlVHlwZTx0eXBlb2YgQ2hvaWNlcz4KICBjaGlsZHJlbjogQ29tcG9uZW50Q2hpbGRyZW4KICB2YWx1ZTogSUNob2ljZQogIG9uT3BlbjogKCkgPT4gdm9pZAogIG9uQ2xvc2U6ICgpID0+IHZvaWQKICBvbkNoYW5nZTogKHZhbHVlOiBJQ2hvaWNlLCBpOiBudW1iZXIpID0+IHZvaWQ%3D)

Incorrect return type.
```coffee
class Store
  getChoicesStore(id: string)?: InstanceType<typeof Choices>
    @elements.find(.id is id)?.options.choices
```
↓↓↓ 0.6.71
```ts
class Store {
  getChoicesStore(id: string): (undefined | (InstanceType extends typeof Choices>
    this.elements.find($ => $.id === id)?.options.choices)){}
}
```
Expected:
```ts
class Store {
  getChoicesStore(id: string): (undefined | InstanceType<typeof Choices>)
    this.elements.find($ => $.id === id)?.options.choices
}
```

**Comment by edemaine** [comment] 2024-02-12 17:47
Turns out to be a duplicate of #984, or at least will also be fixed by #986.

**Closed** 2024-02-13 03:44 UTC
